apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  volumeName: jenkins-pv
  storageClassName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
